AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  StMurilloRLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: StMurilloRLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  MockLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MockLambdaFunction
      Handler: lambda_function.lambda_handler
      Role: !GetAtt StMurilloRLambdaExecutionRole.Arn
      CodeUri: ./src  # Directorio local donde está el código de la Lambda
      Runtime: python3.9
      MemorySize: 512
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /mock
            Method: get

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mock"
